### ISSUE TITLE
Plugin Could not load

### ISSUE THREAD

**Issue by Schmuckiiii** [messageofdeath/CommandNPC#37]
Plugin just doesn't work, when I start the server it appears:

Ambiguous plugin name `CommandNPC' for files `plugins\CommandNPC.jar' and `plugins\CommandNPC-1.9.1.jar' in `plugins'
Could not load 'plugins\PermissionsEx-1.23.3.jar' in folder 'plugins'

What do I do?

**Comment by madtomic** [comment]
Make sure you remove old commandnpc jar file if you recently updated

Also, what version is your server?

**Comment by Schmuckiiii** [comment]
I have never used older versions on this server.
and my server is 1.8.X

**Comment by madtomic** [comment]
Ambiguous plugin name CommandNPC' for files plugins\CommandNPC.jar' and plugins\CommandNPC-1.9.1.jar' in plugins'
Could not load 'plugins\PermissionsEx-1.23.3.jar' in folder 'plugins'

From wha to could see. You have 2 different CommandNPC in the plugin folder.

**Comment by healer-op** [comment]
Could not load 'plugins\CommandNPC-1.9.1.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Citizens
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) [latest1.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292) [latest1.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [latest1.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [latest1.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]

**Comment by halitsever** [comment]
> Could not load 'plugins\CommandNPC-1.9.1.jar' in folder 'plugins'
> org.bukkit.plugin.UnknownDependencyException: Citizens

You need Citizens plugin for using CommandNPC
