### ISSUE TITLE
Bungee error with command /npc cmdadd -o server S

### ISSUE THREAD

**Issue by WillPowerCraft** [messageofdeath/CommandNPC#8]
```
[23:46:31 INFO]: Kreimer issued server command: /npc cmdadd -o /server S
[23:46:31 WARN]: java.lang.IllegalArgumentException: No enum constant me.messageofdeath.CommandNPC.Database.ClickType.both
[23:46:31 WARN]: 	at java.lang.Enum.valueOf(Enum.java:238)
[23:46:31 WARN]: 	at me.messageofdeath.CommandNPC.Database.ClickType.valueOf(ClickType.java:1)
[23:46:31 WARN]: 	at me.messageofdeath.CommandNPC.commands.CitizenCommands.addCmd(CitizenCommands.java:28)
[23:46:31 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:46:31 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[23:46:31 WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:46:31 WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[23:46:31 WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:154)
[23:46:31 WARN]: 	at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:90)
[23:46:31 WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:178)
[23:46:31 WARN]: 	at net.citizensnpcs.Citizens.onCommand(Citizens.java:236)
[23:46:31 WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[23:46:31 WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[23:46:31 WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[23:46:31 WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
[23:46:31 WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[23:46:31 WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[23:46:31 WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[23:46:31 WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[23:46:31 WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[23:46:31 WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[23:46:31 WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[23:46:31 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[23:46:31 WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[23:46:31 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[23:46:31 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[23:46:31 WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by WillPowerCraft** [comment]
ok problem with default generated cnfig.yml with error about click type - ure should HOTfix that

both to BOTH

**Comment by messageofdeath** [comment]
This will be fixed. I forgot to add the method of checking equalsIgnoreCase within the command file. This will be fixed soon.
